### Merging

In [2]:
import numpy as np
import pandas as pd
a=pd.DataFrame({'id':['RA225','RA211','RA249','RA236'],'name':['srima','hyma','jhansi','Akshaya']})
a

id     name
0  RA225    srima
1  RA211     hyma
2  RA249   jhansi
3  RA236  Akshaya

In [3]:
import numpy as np
import pandas as pd
b=pd.DataFrame({'id':['RA225','RA211','RA249','RA236'],'place':['khammam','thuni','thuni','vijaywada']})
b

id      place
0  RA225    khammam
1  RA211      thuni
2  RA249      thuni
3  RA236  vijaywada

In [4]:
pd.merge(a,b)

id     name      place
0  RA225    srima    khammam
1  RA211     hyma      thuni
2  RA249   jhansi      thuni
3  RA236  Akshaya  vijaywada

In [27]:
import numpy as np
import pandas as pd
a=pd.DataFrame({'regno.':['RA225','RA244','RA228','RA236'],'name':['srima','hyma','jhansi','Akshaya'],'place':['1','2','3','4']})
a

regno.     name place
0  RA225    srima     1
1  RA244     hyma     2
2  RA228   jhansi     3
3  RA236  Akshaya     4

In [28]:
import numpy as np
import pandas as pd
b=pd.DataFrame({'regno.':['RA225','RA211','RA249','RA236'],'name':['srima','sai Teja','Aravind','Akshaya']})
b

regno.      name
0  RA225     srima
1  RA211  sai Teja
2  RA249   Aravind
3  RA236   Akshaya

In [29]:
pd.merge(a,b)

regno.     name place
0  RA225    srima     1
1  RA236  Akshaya     4

In [30]:
pd.merge(a,b,on='name')

regno._x     name place regno._y
0    RA225    srima     1    RA225
1    RA236  Akshaya     4    RA236

In [34]:
pd.merge(a,b,on='regno.',how='outer')

regno.   name_x place    name_y
0  RA225    srima     1     srima
1  RA244     hyma     2       NaN
2  RA228   jhansi     3       NaN
3  RA236  Akshaya     4   Akshaya
4  RA211      NaN   NaN  sai Teja
5  RA249      NaN   NaN   Aravind

In [35]:
pd.merge(a,b,on='regno.',how='left')

regno.   name_x place   name_y
0  RA225    srima     1    srima
1  RA244     hyma     2      NaN
2  RA228   jhansi     3      NaN
3  RA236  Akshaya     4  Akshaya

In [36]:
pd.merge(a,b,on='regno.',how='right')

regno.   name_x place    name_y
0  RA225    srima     1     srima
1  RA211      NaN   NaN  sai Teja
2  RA249      NaN   NaN   Aravind
3  RA236  Akshaya     4   Akshaya

In [38]:
pd.merge(a,b,on=['regno.','name'],how='outer')

regno.      name place
0  RA225     srima     1
1  RA244      hyma     2
2  RA228    jhansi     3
3  RA236   Akshaya     4
4  RA211  sai Teja   NaN
5  RA249   Aravind   NaN

In [40]:
pd.merge(a,b,right_index=True,left_index=True)

regno._x   name_x place regno._y    name_y
0    RA225    srima     1    RA225     srima
1    RA244     hyma     2    RA211  sai Teja
2    RA228   jhansi     3    RA249   Aravind
3    RA236  Akshaya     4    RA236   Akshaya

pd.merge(a,b,right_index=True,left_index=True)

### use join function

In [44]:
b.columns=['regno.1','name1']

In [45]:
a.join(b)

regno.     name place regno.1     name1
0  RA225    srima     1   RA225     srima
1  RA244     hyma     2   RA211  sai Teja
2  RA228   jhansi     3   RA249   Aravind
3  RA236  Akshaya     4   RA236   Akshaya

### concatenation

In [46]:
arr1=np.arange(9).reshape((3,3))
arr1

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

In [48]:
arr2=np.arange(9).reshape((3,3))+6
arr2

array([[ 6,  7,  8],
       [ 9, 10, 11],
       [12, 13, 14]])

In [49]:
## column axis
np.concatenate([arr1,arr2],axis=1)

array([[ 6,  7,  8,  6,  7,  8],
       [ 9, 10, 11,  9, 10, 11],
       [12, 13, 14, 12, 13, 14]])

In [50]:
# row axis
np.concatenate([arr1,arr2])

array([[ 6,  7,  8],
       [ 9, 10, 11],
       [12, 13, 14],
       [ 6,  7,  8],
       [ 9, 10, 11],
       [12, 13, 14]])

In [53]:
ser1=pd.Series(np.random.rand(4))
ser1

0    0.845720
1    0.694809
2    0.535604
3    0.007400
dtype: float64

In [54]:
ser1=pd.Series(np.random.rand(4),index=[1,2,3,4])
ser1

1    0.786712
2    0.445378
3    0.538434
4    0.724576
dtype: float64

In [56]:
ser2=pd.Series(np.random.rand(4),)
ser2

0    0.620227
1    0.515089
2    0.476257
3    0.171187
dtype: float64

In [57]:
pd.concat([ser1,ser2])

1    0.786712
2    0.445378
3    0.538434
4    0.724576
0    0.620227
1    0.515089
2    0.476257
3    0.171187
dtype: float64

In [58]:
pd.concat([ser1,ser2],axis=1)

0         1
0       NaN  0.620227
1  0.786712  0.515089
2  0.445378  0.476257
3  0.538434  0.171187
4  0.724576       NaN

In [59]:
pd.concat([ser1,ser2],axis=1,keys=[1,2])

1         2
0       NaN  0.620227
1  0.786712  0.515089
2  0.445378  0.476257
3  0.538434  0.171187
4  0.724576       NaN

In [60]:
pd.concat([ser1,ser2],keys=[1,2])

1  1    0.786712
   2    0.445378
   3    0.538434
   4    0.724576
2  0    0.620227
   1    0.515089
   2    0.476257
   3    0.171187
dtype: float64

In [69]:
arr1=pd.DataFrame(np.random.rand(9).reshape(3,3),index=[1,2,3],columns=['A','B','C'])
arr1

A         B         C
1  0.460334  0.145110  0.080681
2  0.786399  0.125225  0.875955
3  0.891255  0.309878  0.900764

In [70]:
arr2=pd.DataFrame(np.random.rand(9).reshape(3,3),index=[4,5,6],columns=['A','B','C'])
arr2

A         B         C
4  0.735327  0.003816  0.503599
5  0.346327  0.815008  0.627530
6  0.842505  0.363653  0.794575

In [71]:
pd.concat([arr1,arr2])

A         B         C
1  0.460334  0.145110  0.080681
2  0.786399  0.125225  0.875955
3  0.891255  0.309878  0.900764
4  0.735327  0.003816  0.503599
5  0.346327  0.815008  0.627530
6  0.842505  0.363653  0.794575

In [72]:
pd.concat([arr1,arr2],axis=1)

A         B         C         A         B         C
1  0.460334  0.145110  0.080681       NaN       NaN       NaN
2  0.786399  0.125225  0.875955       NaN       NaN       NaN
3  0.891255  0.309878  0.900764       NaN       NaN       NaN
4       NaN       NaN       NaN  0.735327  0.003816  0.503599
5       NaN       NaN       NaN  0.346327  0.815008  0.627530
6       NaN       NaN       NaN  0.842505  0.363653  0.794575