In [2]:

import numpy as np

## create a array

In [6]:
a=np.array([1,2,3,4,5])
print(a)

[1 2 3 4 5]


In [25]:
#using ones(),zeros()function to create data
c=np.zeros((3,3))
print(c)

[[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]


In [29]:
#using arange()function
c=np.arange(10)
print(c)

[0 1 2 3 4 5 6 7 8 9]


In [31]:
#format for arange(start,stop,iteration)
c=np.arange(0,12,0.6)
print(c)

[ 0.   0.6  1.2  1.8  2.4  3.   3.6  4.2  4.8  5.4  6.   6.6  7.2  7.8
  8.4  9.   9.6 10.2 10.8 11.4]


In [3]:
#reshaping the array using reshape() function syntax reshape(dimensions,rows,columns)
d=np.arange(0,8).reshape(2,2,2)
print(d)

[[[0 1]
  [2 3]]

 [[4 5]
  [6 7]]]


In [37]:
#linspace function() syntax:linspace(start,stop,no.of values needed as output)
e=np.linspace(0,10,6)
print(e)

[ 0.  2.  4.  6.  8. 10.]


In [38]:
f=np.random.random(5)
print(f)

[0.75475383 0.45398528 0.69337252 0.18900566 0.76641318]


In [39]:
f=np.random.random((5,5))
print(f)

[[0.43999923 0.50937296 0.66783312 0.42819149 0.98374344]
 [0.94616653 0.57521305 0.09359982 0.03199616 0.17861918]
 [0.51767853 0.88516645 0.96853022 0.16815243 0.69722752]
 [0.38112122 0.51576449 0.96420415 0.80538136 0.42794086]
 [0.26029708 0.8624247  0.60035736 0.86928945 0.54993258]]


## find 'a' type using type function

In [7]:
type(a)

numpy.ndarray

## find the datatype,size,shape and dimensions of "a"

In [13]:
a.dtype

dtype('int32')

In [14]:
a.size

5

In [15]:
a.ndim

1

In [16]:
a.shape

(5,)

## creating 2 dimensional array and finding its datatype,size,shape and dimensions

In [17]:
b=np.array([[1,2,3,4,5],[6,7,8,9,10]])
print(b)

[[ 1  2  3  4  5]
 [ 6  7  8  9 10]]


In [18]:
b.dtype

dtype('int32')

In [19]:
b.size

10

In [20]:
b.ndim

2

In [21]:
b.itemsize

4

In [22]:
b.shape

(2, 5)

### basic operations

In [46]:
a=np.arange(10)
print(a)

[0 1 2 3 4 5 6 7 8 9]


In [41]:
a+2

array([ 2,  3,  4,  5,  6,  7,  8,  9, 10, 11])

In [42]:
a-5

array([-5, -4, -3, -2, -1,  0,  1,  2,  3,  4])

In [57]:
# we can use increment and decrement operators for adding also
a+=5
print(a)

[ 5  6  7  8  9 10 11 12 13 14]


In [67]:
a-=5
print(a)

[0 1 2 3 4 5 6 7 8 9]


In [68]:
a*2

array([ 0,  2,  4,  6,  8, 10, 12, 14, 16, 18])

In [69]:
a*np.sin(a)


array([ 0.        ,  0.84147098,  1.81859485,  0.42336002, -3.02720998,
       -4.79462137, -1.67649299,  4.59890619,  7.91486597,  3.70906637])

In [70]:
a*np.sqrt(a)

array([ 0.        ,  1.        ,  2.82842712,  5.19615242,  8.        ,
       11.18033989, 14.69693846, 18.52025918, 22.627417  , 27.        ])

In [61]:
A=np.arange(9).reshape((3,3))
print(A)

[[0 1 2]
 [3 4 5]
 [6 7 8]]


In [62]:
B=np.ones((3,3))
print(B)

[[1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]]


In [63]:
A*B

array([[0., 1., 2.],
       [3., 4., 5.],
       [6., 7., 8.]])

In [64]:
A-B

array([[-1.,  0.,  1.],
       [ 2.,  3.,  4.],
       [ 5.,  6.,  7.]])

In [65]:
np.dot(A, B)

array([[ 3.,  3.,  3.],
       [12., 12., 12.],
       [21., 21., 21.]])

In [66]:
A.dot(B)

array([[ 3.,  3.,  3.],
       [12., 12., 12.],
       [21., 21., 21.]])

### Universal functions

In [71]:
k=np.arange(1,5)
print(k)

[1 2 3 4]


In [72]:
np.sum(k)

10

In [73]:
np.log(k)

array([0.        , 0.69314718, 1.09861229, 1.38629436])

In [74]:
np.sqrt(k)

array([1.        , 1.41421356, 1.73205081, 2.        ])

In [75]:
np.cos(k)

array([ 0.54030231, -0.41614684, -0.9899925 , -0.65364362])

In [76]:
np.sin(k)

array([ 0.84147098,  0.90929743,  0.14112001, -0.7568025 ])

### Aggregate functions

In [79]:
l=np.array((1,2,3,4,5,6))
print(l)

[1 2 3 4 5 6]


In [81]:
l.sum()

21

In [82]:
l.max()

6

In [83]:
l.std()

1.707825127659933

In [84]:
l.var()

2.9166666666666665

In [87]:
l.mean()

3.5

### indexing

In [91]:
o=np.linspace(0,10,6)
print(o)

[ 0.  2.  4.  6.  8. 10.]


In [92]:
o[2]

4.0

In [94]:
o[[2,4,5]]

array([ 4.,  8., 10.])

In [95]:
u=np.arange(1,10).reshape(3,3)
print(u)

[[1 2 3]
 [4 5 6]
 [7 8 9]]


In [96]:
u[1,2]

6

In [97]:
u[[0,1],[0,1]]

array([1, 5])

### slicing

In [98]:
m=np.arange(1,10)
print(m)

[1 2 3 4 5 6 7 8 9]


In [100]:
m[1::2]

array([2, 4, 6, 8])

In [101]:
m[:6:2]

array([1, 3, 5])

In [102]:
u[0,:]

array([1, 2, 3])

In [103]:
u[:,0]

array([1, 4, 7])

In [104]:
u[0:2,0:2]

array([[1, 2],
       [4, 5]])