### iterating an array

In [2]:
import numpy as np
a=np.array([1,2,3,4,5])
print(a)

[1 2 3 4 5]


In [3]:
for i in a:
    print(i)

1
2
3
4
5


In [6]:
b=np.arange(1,10).reshape(3,3)
print(b)

[[1 2 3]
 [4 5 6]
 [7 8 9]]


In [9]:
for x in b:
    for y in x:
        print(y)

1
2
3
4
5
6
7
8
9


In [11]:
arr=np.array([[1,2,3],[4,5,6]])
print(arr)

[[1 2 3]
 [4 5 6]]


In [13]:
for x in arr:
    for y in x:
        print(y)

1
2
3
4
5
6


In [18]:
#iterating with 3-D array
a=np.arange(0,12).reshape(3,2,2)
print(a)

[[[ 0  1]
  [ 2  3]]

 [[ 4  5]
  [ 6  7]]

 [[ 8  9]
  [10 11]]]


In [38]:
np.apply_along_axis(np.mean,axis=0,arr=a)

array([[4., 5.],
       [6., 7.]])

In [39]:
np.apply_along_axis(np.mean,axis=1,arr=a)

array([[ 1.,  2.],
       [ 5.,  6.],
       [ 9., 10.]])

In [19]:
for x in a:
    for y in x:
        for z in y:
            print(z)

0
1
2
3
4
5
6
7
8
9
10
11


In [31]:
A=np.arange(10,19).reshape((3,3))
print(A)

[[10 11 12]
 [13 14 15]
 [16 17 18]]


In [32]:
def foo(x):
    return x/2

In [33]:
np.apply_along_axis(foo,axis=0,arr=A)

array([[5. , 5.5, 6. ],
       [6.5, 7. , 7.5],
       [8. , 8.5, 9. ]])

In [37]:
np.apply_along_axis(np.mean,axis=1,arr=A)

array([11., 14., 17.])

In [40]:
# using boolean operators for extracting elements
A=np.random.random((4,4))
print(A)

[[0.99152642 0.98806343 0.67846707 0.92354584]
 [0.89003973 0.30114925 0.57578871 0.04864797]
 [0.77455907 0.68922232 0.82285681 0.06820559]
 [0.81102442 0.56941098 0.62734011 0.48927491]]


In [41]:
A<0.5

array([[False, False, False, False],
       [False,  True, False,  True],
       [False, False, False,  True],
       [False, False, False,  True]])

In [42]:
A[A<0.5]

array([0.30114925, 0.04864797, 0.06820559, 0.48927491])

In [43]:
# shape manipulation
A=np.random.random(12)
print(A)

[0.43616604 0.63618975 0.3789309  0.67629827 0.99227291 0.33420921
 0.85006832 0.80130666 0.93636492 0.17922826 0.6765524  0.33935619]


In [45]:
b=A.reshape(3,4)
print(b)

[[0.43616604 0.63618975 0.3789309  0.67629827]
 [0.99227291 0.33420921 0.85006832 0.80130666]
 [0.93636492 0.17922826 0.6765524  0.33935619]]


In [46]:
#converting to 1-D dimensional using raval()
b=b.ravel()
print(b)

[0.43616604 0.63618975 0.3789309  0.67629827 0.99227291 0.33420921
 0.85006832 0.80130666 0.93636492 0.17922826 0.6765524  0.33935619]
